production:
    DATABASE_URL: ENC[AES256_GCM,data:rOjIm4eKCPyaPIANDjGqnOWbFObZs2HZYOqtd6A=,iv:ece8wVA++ngSlTBSTnYBl+7txJ21e3Ln4KCCKJWaVGU=,tag:OtjcLow2GRuAvsxLjQH/DQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:HF36LSag6aTiWtWphQ82Sw==,iv:i9qV2AFMNTJlEnSlthOJ8KvQ98374wXSd3B0JWNxY0o=,tag:VCmJS9hNitVp0mr88BPgRQ==,type:str]
    VERCEL_TOKEN: ENC[AES256_GCM,data:zZ2TbmRUyexeIXEKLAkDzPi1pTVPvj+uZw3wSSWXNGolptXb5oIZYceXaxHV3wxU6EhMz0Aj9lAxOvh3,iv:AMssfJmeNHYm55ijFiAtOLYSCGCtFOJhZwrvc2Vusmo=,tag:Tcok0omtmwUaY2ks7u0FUA==,type:str]
    VERCEL_PROJECT_ID: ENC[AES256_GCM,data:gM0PWdYgqfndhSM0x6PujZjH/OkXAZaUx9EBab3NMkI=,iv:3t1cL2PbZPrL3CSyOhAvBrvv4hnCzr4Efx5XudeHT+8=,tag:sMcuSifrWGKHmxbDlVIcmw==,type:str]
    VERCEL_ORG_ID: ENC[AES256_GCM,data:W+UGBXjkDK44KDG0eQnXngz1Ya/R/6RYUHmBXdc=,iv:jX8RA87PLfMsgaOo/ldvkm5kpClxI1aZch4dTBODZbY=,tag:XdThdjONjRrdSf9TXWyOew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10clg85jd364uwrnuznsgllakff2shp0ef07k5em559wtmtj2sfvsy3hfm2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbDRTbkpybkxzOGRMMHE0
            YWREOXZOTm14ZkVKazVwMmJxdFN3WVJkdndJCkp5cFhYb21nZHEzaGI0T1did3VO
            MUJVRkNLdE9BZS8vRlBsWWFrODhmWWcKLS0tIEVOcW9BU2YwSXN6WkdoQTBjQ3BF
            YTVzNjVPeU1PSlBmanh0TlBUZzlrNDAKUeSRNoh+O77CFRtgbqmtsMj3BKlKostT
            vm1DNFGnUfMcaeLOS12ORxfw+/9VRSu54JEbNBq1xoadH9VKUJdUOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T12:14:23Z"
    mac: ENC[AES256_GCM,data:fozQwu4AMVSEIF6sjpXXK4UDKtpD7ATmHaXavl4Q4pUPzuCOOEdgXPChg8W2sJsb/C/fopEROPKZJmu4vEJbJUgfuSkwyv1jLY7MkDEdvEW2BPiTP0gq7G8dzuUyZTgE0CaW+LNlmi/4+LtBLOIbWatBvZzLbUFTIUMBsQHENmU=,iv:YuNQRcFFNeIt/Ep3IWjpCBytNAh3Aw5NL5efsRL9wU8=,tag:nYOPnQ2BI6/JKJyvdRCQLg==,type:str]
    pgp: []
    encrypted_regex: ^(DATABASE_URL|JWT_SECRET|VERCEL_TOKEN|VERCEL_PROJECT_ID|VERCEL_ORG_ID)$
    version: 3.9.0
