creation_rules:
  - path_regex: ^\.github/secrets-prod\.yaml$
    encrypted_regex: '^(DATABASE_URL|JWT_SECRET|VERCEL_TOKEN|VERCEL_PROJECT_ID|VERCEL_ORG_ID)$'
    age: age10clg85jd364uwrnuznsgllakff2shp0ef07k5em559wtmtj2sfvsy3hfm2
